### ISSUE TITLE
`SimpleSpec` with Caret and Prerelease Wrong Behavior

### ISSUE THREAD

**Issue by hfudev** [rbarrois/python-semanticversion#128]
Hi, I found two issues when using `SimpleSpec` with caret and prerelease.

here's the example

```python
from semantic_version import Version, SimpleSpec

spec = SimpleSpec('^0.0.2-alpha')
print(spec.clause)

# 1st issue
# got AllOf(Range('<', Version('0.0.2')), Range('>=', Version('0.0.2-alpha')))
# which should be >=0.0.2-alpha, <0.0.3 according to https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

print(spec.match(Version('0.0.2-beta')))

# 2nd issue
# got False
# should be True

print(Version('0.0.2-beta') > Version('0.0.2-alpha'))

# got True
# this is correct
```

Please take a look. Thanks!

**Comment by hfudev** [comment]
@pombredanne thanks for your reply.

I'm asking because according to the doc, the `SimpleSpec` inherits the caret symbol from the NPM extension, so it may be essential to keep the behavior consistent between them.

**Comment by pombredanne** [comment]
@hfudev SimpleSpec is not for Python IMHO. 

FWIW, I have seen tilde and caret version ranges syntax in node-semver, rubygems-semver, Python pep440 (no caret) and composer-semver and all of the them are different even if if in a subtle way.   And Python versions are not semver and the Python version ranges are not the same node-semver at all (even though it may look a bit like node-semver ranges).

In univers (a library that reuses this library) you can see how we implement support 
- for PyPI version ranges: https://github.com/nexB/univers/blob/6ad300ea515f99ffaae8b6a160724c32f027b5c0/src/univers/version_range.py#L495
- and for PyPI versions: https://github.com/nexB/univers/blob/6ad300ea515f99ffaae8b6a160724c32f027b5c0/src/univers/versions.py#L176

One a side note I would strongly discourage using tilde in Python ranges (and tilde and carets elsewhere) and in general upper bounds on version ranges anywhere because of https://iscinumpy.dev/post/bound-version-constraints/

**Comment by hfudev** [comment]
Thanks for your patience and the blog you shared. Somehow changed my mind after reading this.
