### ISSUE TITLE
next_major() bug when minor=0 and patch=0 and prerelease is not none

### ISSUE THREAD

**Issue by jakubka** [rbarrois/python-semanticversion#64]
Hi,

I think there is a bug in `next_major()` function when certain conditions are met:

```
In [32]: semantic_version.Version("3.0.0").next_major()
Out[32]: Version('4.0.0') # Correct

In [33]: semantic_version.Version("3.0-slim",partial=True).next_major()
Out[33]: Version('4.0.0') # Correct

In [34]: semantic_version.Version("3.0",partial=True).next_major()
Out[34]: Version('4.0.0') # Correct

In [31]: semantic_version.Version("3.0.0-slim").next_major()
Out[31]: Version('3.0.0') # WRONG - should be 4.0.0

In [35]: v = semantic_version.Version("3.0.0-slim")
In [36]: v.prerelease = None
In [37]: v.next_major()
Out[37]: Version('4.0.0') # Correct
```

Is it really a bug or am I missing something?

Thanks

**Comment by guboi72** [comment]
I agree, Documentation need to be upgraded with proper use.

**Comment by rbarrois** [comment]
I've just fixed it, but the other way around: ``next_major()`` is defined as "the smallest of all 'pure' major that are strictly greater than the current version".

I know this is a tricky point, and I couldn't find any formal definition of the "next" version within semver.

Since ``Version('3.0.0')`` is a pure major version, and ``Version('3.0.0') > Version('3.0.0-pre')``, then ``Version('3.0.0')`` is indeed the proper "next major" for ``3.0.0-pre`` (no other "pure major" could come between them).
